env:
  global:
    - CC_TEST_REPORTER_ID=6849b1c065f605db4d6b154a853e919eb5da83bc4e02413050d84d48d35eec11
language: node_js
node_js: 
  - '10'
services:
  - postgresql

cache:
  directories:
    - "node_modules"
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER quickcredit WITH PASSWORD 'barcelona';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:

  - npm run test

after_success:

  -npm run nyc

after_script:

  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
