export default {
  users: [
    {
      id: 1,
      email: 'test@tester.com',
      firstName: 'Adeogo',
      lastName: 'Adejana',
      password: 'Adeogoadejan',
      address: 'Victoria island',
      type: 'admin',
      isAdmin: true,
    },
    {
      id: 2,
      email: 'jimiagbaje@gmail.com',
      firstName: 'jimi',
      lastName: 'agbaje',
      password: 'jimiagbaje',
      address: 'lekki',
      type: 'client',
      isAdmin: false,
    },
    {
      id: 3,
      email: 'donaldoduke@gmail.com',
      firstName: 'donaldo',
      lastName: 'duke',
      password: 'donaldoduke',
      address: 'yaba',
      type: 'client',
      isAdmin: false,
    },
    {
      id: 4,
      email: 'feladurotoye@gmail.com',
      firstName: 'fela',
      lastName: 'durotoye',
      password: 'feladurotoye',
      address: 'ketu',
      type: 'admin',
      isAdmin: false,
    },
  ],
};
